import Footer from './Footer'
import Header from './Header'


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function Layout({ children }) {
  return (
       <>
        <Header/>
        <div className='mainbody'>
        {children}
        </div>
        <Footer/>
        </>
  )
}
